version: '2.2'
services:
  api:
    build: ./backend
    environment:
      - HOST=12.0.0.150
      - USER=root
      - PASSWORD=
      - DATABASE=todo-db
      - PORT=3306
    ports:
      - "6001:6001"
  webapp:
    build: ./frontend
    environment:
      - API_URL=http://12.0.0.150:6001
    depends_on:
      - api
    ports:
      - "6002:6002"

